export { generalChangeNote } from './generalChangeNote';
export type { GeneralChangeNoteProps } from './generalChangeNote';
export { generalChangeUserName } from './generalChangeUserName';
export type { GeneralChangeUserNameProps } from './generalChangeUserName';
export { generalChangeName } from './generalChangeName';
export type { GeneralChangeNameProps } from './generalChangeName';
export { generalChangeLastName } from './generalChangeLastName';
export type { GeneralChangeLastNameProps } from './generalChangeLastName';
export { generalChangePassword } from './generalChangePassword';
export type { GeneralChangePasswordProps } from './generalChangePassword';
export { generalChangeDescription } from './generalChangeDescription';
export type { GeneralChangeDescriptionProps } from './generalChangeDescription';
export { generalChangeAddress } from './generalChangeAddress';
export type { GeneralChangeAddressProps } from './generalChangeAddress';
export { generalChangeAddressType } from './generalChangeAddressType';
export type { GeneralChangeAddressTypeProps } from './generalChangeAddressType';
export { generalChangeCityStateCountry } from './generalChangeCityStateCountry';
export type { GeneralChangeCityStateCountryProps } from './generalChangeCityStateCountry';
export { generalChangeCityOptions } from './generalChangeCityOptions';
export type { GeneralChangeCityOptionsProps } from './generalChangeCityOptions';
export { generalChangeStateCountryOptions } from './generalChangeStateCountryOptions';
export type { GeneralChangeStateCountryOptionsProps } from './generalChangeStateCountryOptions';
export { generalChangePostCode } from './generalChangePostCode';
export type { GeneralChangePostCodeProps } from './generalChangePostCode';
export { generalChangeSite } from './generalChangeSite';
export type { GeneralChangeSiteProps } from './generalChangeSite';
export { generalChangeParentId } from './generalChangeParentId';
export type { GeneralChangeParentIdProps } from './generalChangeParentId';
export { generalChangePhoto } from './generalChangePhoto';
export type { GeneralChangePhotoProps } from './generalChangePhoto';
export { generalChangeGalleryPhoto } from './generalChangeGalleryPhoto';
export type { GeneralChangeGalleryPhotoProps } from './generalChangeGalleryPhoto';
export { generalChangeStatus } from './generalChangeStatus';
export type { GeneralChangeStatusProps } from './generalChangeStatus';
export { generalChangeCurrenciesSymbol } from './generalChangeCurrenciesSymbol';
export type { GeneralChangeCurrenciesSymbolProps } from './generalChangeCurrenciesSymbol';
export { generalChangeTypeDocumentIdId } from './generalChangeTypeDocumentIdId';
export type { GeneralChangeTypeDocumentIdIdProps } from './generalChangeTypeDocumentIdId';
export { generalChangeDocumentIdIndex } from './generalChangeDocumentIdIndex';
export type { GeneralChangeDocumentIdIndexProps } from './generalChangeDocumentIdIndex';
export { generalChangeDocumentIdDigit } from './generalChangeDocumentIdDigit';
export type { GeneralChangeDocumentIdDigitProps } from './generalChangeDocumentIdDigit';
export { generalChangeEmail } from './generalChangeEmail';
export type { GeneralChangeEmailProps } from './generalChangeEmail';
export { generalChangePhone } from './generalChangePhone';
export type { GeneralChangePhoneProps } from './generalChangePhone';
export { generalChangeType } from './generalChangeType';
export type { GeneralChangeTypeProps } from './generalChangeType';
export { generalChangeCurrenciesId } from './generalChangeCurrenciesId';
export type { GeneralChangeCurrenciesIdProps } from './generalChangeCurrenciesId';
export { generalChangeCurrenciesDecimalNumbers } from './generalChangeCurrenciesDecimalNumbers';
export type { GeneralChangeCurrenciesDecimalNumbersProps } from './generalChangeCurrenciesDecimalNumbers';
export { generalChangeTaxes } from './generalChangeTaxes';
export type { GeneralChangeTaxesProps } from './generalChangeTaxes';
export { generalChangeWebSite } from './generalChangeWebSite';
export type { GeneralChangeWebSiteProps } from './generalChangeWebSite';
export { generalChangeAreaCode } from './generalChangeAreaCode';
export type { GeneralChangeAreaCodeProps } from './generalChangeAreaCode';
export { generalChangeRoles } from './generalChangeRoles';
export type { GeneralChangeRolesProps } from './generalChangeRoles';
export { generalChanceIsActive } from './generalChanceIsActive';
export type { GeneralChanceIsActiveProps } from './generalChanceIsActive';
export { generalChangeCategoryId } from './generalChangeCategoryId';
export type { GeneralChangeCategoryIdProps } from './generalChangeCategoryId';
export { generalChangeTags } from './generalChangeTags';
export type { GeneralChangeTagsProps } from './generalChangeTags';
export { generalChangeSku } from './generalChangeSku';
export type { GeneralChangeSkuProps } from './generalChangeSku';
export { generalChangeSalesPrice } from './generalChangeSalesPrice';
export type { GeneralChangeSalesPriceProps } from './generalChangeSalesPrice';
export { generalChangeOfferPrice } from './generalChangeOfferPrice';
export type { GeneralChangeOfferPriceProps } from './generalChangeOfferPrice';
export { generalChangeCost } from './generalChangeCost';
export type { GeneralChangeCostProps } from './generalChangeCost';
export { generalChangeTaxStatus } from './generalChangeTaxStatus';
export type { GeneralChangeTaxStatusProps } from './generalChangeTaxStatus';
export { generalChangeTaxClass } from './generalChangeTaxClass';
export type { GeneralChangeTaxClassProps } from './generalChangeTaxClass';
export { generalChangePackageType } from './generalChangePackageType';
export type { GeneralChangePackageTypeProps } from './generalChangePackageType';
export { generalChangeQtyPack } from './generalChangeQtyPack';
export type { GeneralChangeQtyPackProps } from './generalChangeQtyPack';
export { generalChangeUndCbm } from './generalChangeUndCbm';
export type { GeneralChangeUndCbmProps } from './generalChangeUndCbm';
export { generalChangeAttributes } from './generalChangeAttributes';
export type { GeneralChangeAttributesProps } from './generalChangeAttributes';
export { generalChangeLink } from './generalChangeLink';
export type { GeneralChangeLinkProps } from './generalChangeLink';
export { generalChangeVisibility } from './generalChangeVisibility';
export type { GeneralChangeVisibilityProps } from './generalChangeVisibility';
export { generalChangeWeight } from './generalChangeWeight';
export type { GeneralChangeWeightProps } from './generalChangeWeight';
export { generalChangeHeight } from './generalChangeHeight';
export type { GeneralChangeHeightProps } from './generalChangeHeight';
export { generalChangeWidth } from './generalChangeWidth';
export type { GeneralChangeWidthProps } from './generalChangeWidth';
export { generalChangeLength } from './generalChangeLength';
export type { GeneralChangeLengthProps } from './generalChangeLength';
export { generalChangeCatalogOrder } from './generalChangeCatalogOrder';
export type { GeneralChangeCatalogOrderProps } from './generalChangeCatalogOrder';
export { generalChangeTaxClasses } from './generalChangeTaxClasses';
export type { GeneralChangeTaxClassesProps } from './generalChangeTaxClasses';
export { generalChangeRate } from './generalChangeRate';
export type { GeneralChangeRateProps } from './generalChangeRate';
export { generalChangeCustomerId } from './generalChangeCustomerId';
export type { GeneralChangeCustomerIdProps } from './generalChangeCustomerId';
export { generalChangeReferredId } from './generalChangeReferredId';
export type { GeneralChangeReferredIdProps } from './generalChangeReferredId';
export { generalChangeShippingAreas } from './generalChangeShippingAreas';
export type { GeneralChangeShippingAreasProps } from './generalChangeShippingAreas';
export { generalChangeShippingTimeDays } from './generalChangeShippingTimeDays';
export type { GeneralChangeShippingTimeDaysProps } from './generalChangeShippingTimeDays';
export { generalChangeAvailableShippingServices } from './generalChangeAvailableShippingServices';
export type { GeneralChangeAvailableShippingServicesProps } from './generalChangeAvailableShippingServices';
export { generalChangeRegion } from './generalChangeRegion';
export type { GeneralChangeRegionProps } from './generalChangeRegion';
export { generalChangeSupplierId } from './generalChangeSupplierId';
export type { GeneralChangeSupplierIdProps } from './generalChangeSupplierId';
export { generalChangeExpensesTypeId } from './generalChangeExpensesTypeId';
export type { GeneralChangeExpensesTypeIdProps } from './generalChangeExpensesTypeId';
export { generalChangeProjectsId } from './generalChangeProjectsId';
export type { GeneralChangeProjectsIdProps } from './generalChangeProjectsId';
export { generalChangeCashRegisterType } from './generalChangeCashRegisterType';
export type { GeneralChangeCashRegisterTypeProps } from './generalChangeCashRegisterType';
export { generalChangeBankName } from './generalChangeBankName';
export type { GeneralChangeBankNameProps } from './generalChangeBankName';
export { generalChangeAccountNumber } from './generalChangeAccountNumber';
export type { GeneralChangeAccountNumberProps } from './generalChangeAccountNumber';
export { generalChangeAccountType } from './generalChangeAccountType';
export type { GeneralChangeAccountTypeProps } from './generalChangeAccountType';
export { generalChangeCurrency } from './generalChangeCurrency';
export type { GeneralChangeCurrencyProps } from './generalChangeCurrency';
export { generalChangeSettings } from './generalChangeSettings';
export type { GeneralChangeSettingsProps } from './generalChangeSettings';
export { generalChangeBankType } from './generalChangeBankType';
export type { GeneralChangeBankTypeProps } from './generalChangeBankType';
export { generalChangeCreditLimit } from './generalChangeCreditLimit';
export type { GeneralChangeCreditLimitProps } from './generalChangeCreditLimit';
export { generalChangeCreditTimeToPay } from './generalChangeCreditTimeToPay';
export type { GeneralChangeCreditTimeToPayProps } from './generalChangeCreditTimeToPay';
export { generalChangePhotoWebSockets } from './generalChangePhotoWebSockets';
export type { GeneralChangePhotoWebSocketsProps } from './generalChangePhotoWebSockets';
export { generalChangeGalleryPhotoWebSockets } from './generalChangeGalleryPhotoWebSockets';
export type { GeneralChangeGalleryPhotoWebSocketsProps } from './generalChangeGalleryPhotoWebSockets';
