export {
  useGafpriApiEntity,
  useGafpriAttributesEntity,
  useGafpriDataEntity,
  useGafpriPaginationsEntity,
  useGafpriPagesEntity,
} from './entity';
export type {
  UseGafpriApiEntityReturn,
  UseGafpriApiEntityProps,
  UseGafpriAttributesEntityReturn,
  typeDocumentId,
  DocumentIdAttributes,
  AddressAttributes,
  EntityAttributes,
  UseGafpriAttributesEntityProps,
  UseGafpriDataEntityReturn,
  UseGafpriDataEntityProps,
  UseGafpriPaginationsEntityReturn,
  UseGafpriPaginationsEntityProps,
  UseGafpriPagesEntityReturn,
  UseGafpriPagesEntityProps,
  UseGafpriApiEntityReturnDataCreate,
  UseGafpriApiEntityReturnDataUpdate,
  UseGafpriApiEntityReturnDataDelete,
} from './entity';
export {
  useGafpriAttributesProducts,
  useGafpriSubPagesProducts,
  useGafpriPagesProducts,
  useGafpriDataProducts,
  useGafpriApiProducts,
  useGafpriPaginationsProducts,
} from './products';
export type {
  UseGafpriAttributesProductsReturn,
  UseGafpriAttributesProductsProps,
  UseGafpriSubPagesProductsReturn,
  UseGafpriPagesProductsReturn,
  UseGafpriPagesProductsProps,
  UseGafpriDataProductsReturn,
  UseGafpriDataProductsProps,
  ProductsAttributes,
  UseGafpriApiProductsReturn,
  UseGafpriApiProductsProps,
  UseGafpriPaginationsProductsReturn,
  UseGafpriPaginationsProductsProps,
} from './products';
export {
  useGafpriAttributesOrderItems,
  useGafpriAttributesBudgetItems,
  useGafpriAttributesOrderReturnItems,
} from './productsItems';
export type {
  UseGafpriAttributesOrderItemsReturn,
  UseGafpriAttributesOrderItemsProps,
  OrderItemsAttributes,
  UseGafpriAttributesBudgetItemsReturn,
  UseGafpriAttributesBudgetItemsProps,
  BudgetItemsAttributes,
  UseGafpriAttributesOrderReturnItemsReturn,
  UseGafpriAttributesOrderReturnItemsProps,
  OrderReturnItemsAttributes,
} from './productsItems';
export {
  useGafpriAttributesTaxClasses,
  useGafpriDataTaxClasses,
  useGafpriApiTaxClasses,
  useGafpriPaginationsTaxClasses,
  useGafpriPagesTaxClasses,
  useGafpriApiTaxRates,
  useGafpriAttributesTaxRates,
  useGafpriDataTaxRates,
  useGafpriPaginationsTaxRates,
  useGafpriPagesTaxRates,
} from './taxes';
export type {
  UseGafpriAttributesTaxClassesReturn,
  UseGafpriDataTaxClassesReturn,
  UseGafpriDataTaxClassesProps,
  TaxClassesAttributes,
  UseGafpriApiTaxClassesReturn,
  UseGafpriApiTaxClassesProps,
  UseGafpriPaginationsTaxClassesReturn,
  UseGafpriPaginationsTaxClassesProps,
  UseGafpriPagesTaxClassesReturn,
  UseGafpriPagesTaxClassesProps,
  UseGafpriAttributesTaxRatesReturn,
  UseGafpriDataTaxRatesReturn,
  UseGafpriDataTaxRatesProps,
  TaxRatesAttributes,
  UseGafpriApiTaxRatesReturn,
  UseGafpriApiTaxRatesProps,
  UseGafpriPaginationsTaxRatesReturn,
  UseGafpriPagesTaxRatesReturn,
  UseGafpriPagesTaxRatesProps,
} from './taxes';
export {
  useGafpriAttributesOrder,
  useGafpriPagesOrder,
  useGafpriApiOrder,
  useGafpriDataOrder,
  useGafpriPaginationsOrder,
} from './order';
export type {
  UseGafpriAttributesOrderReturn,
  UseGafpriAttributesOrderProps,
  UseGafpriPagesOrderReturn,
  UseGafpriPagesOrderProps,
  UseGafpriApiOrderReturn,
  UseGafpriApiOrderProps,
  UseGafpriDataOrderReturn,
  UseGafpriDataOrderProps,
  OrderAttributes,
  UseGafpriPaginationsOrderReturn,
  UseGafpriPaginationsOrderProps,
} from './order';
export { useGafpriPagesSalesModule } from './salesModule';
export type { UseGafpriPagesSalesModuleReturn } from './salesModule';
export {
  useGafpriAttributesBudget,
  useGafpriPagesBudget,
  useGafpriDataBudget,
  useGafpriPaginationsBudget,
  useGafpriApiBudget,
} from './budget';
export type {
  UseGafpriAttributesBudgetReturn,
  UseGafpriAttributesBudgetProps,
  UseGafpriPagesBudgetReturn,
  UseGafpriPagesBudgetProps,
  UseGafpriDataBudgetReturn,
  UseGafpriDataBudgetProps,
  BudgetAttributes,
  UseGafpriPaginationsBudgetReturn,
  UseGafpriPaginationsBudgetProps,
  UseGafpriApiBudgetReturn,
  UseGafpriApiBudgetProps,
} from './budget';
export {
  useGafpriAttributesShippingMethods,
  useGafpriPagesShippingMethods,
  useGafpriDataShippingMethods,
  useGafpriApiShippingMethods,
  useGafpriPaginationsShippingMethods,
  useGafpriAttributesShippingAreas,
  useGafpriPagesShippingAreas,
  useGafpriDataShippingAreas,
  useGafpriApiShippingAreas,
  useGafpriPaginationsShippingAreas,
} from './shipping';
export type {
  UseGafpriAttributesShippingMethodsReturn,
  UseGafpriPagesShippingMethodsReturn,
  UseGafpriPagesShippingMethodsProps,
  UseGafpriDataShippingMethodsReturn,
  ShippingMethodsAttributes,
  UseGafpriDataShippingMethodsProps,
  UseGafpriApiShippingMethodsReturn,
  UseGafpriApiShippingMethodsProps,
  UseGafpriPaginationsShippingMethodsReturn,
  UseGafpriAttributesShippingAreasReturn,
  UseGafpriPagesShippingAreasReturn,
  UseGafpriPagesShippingAreasProps,
  ShippingAreasAttributes,
  UseGafpriDataShippingAreasProps,
  UseGafpriDataShippingAreasReturn,
  UseGafpriApiShippingAreasReturn,
  UseGafpriApiShippingAreasProps,
  UseGafpriPaginationsShippingAreasReturn,
  UseGafpriPaginationsShippingAreasProps,
} from './shipping';
export {
  useGafpriApiProjects,
  useGafpriPagesProjects,
  useGafpriAttributesProjects,
  useGafpriDataProjects,
  useGafpriPaginationsProjects,
} from './projects';
export type {
  UseGafpriApiProjectsProps,
  UseGafpriApiProjectsReturn,
  UseGafpriPagesProjectsProps,
  UseGafpriPagesProjectsReturn,
  UseGafpriAttributesProjectsReturn,
  UseGafpriDataProjectsReturn,
  ProjectsAttributes,
  UseGafpriPaginationsProjectsProps,
  UseGafpriPaginationsProjectsReturn,
} from './projects';
export {
  useGafpriAttributesStorage,
  useGafpriPagesStorage,
  useGafpriDataStorage,
  useGafpriApiStorage,
  useGafpriPaginationsStorage,
} from './storage';
export type {
  UseGafpriAttributesStorageProps,
  UseGafpriAttributesStorageReturn,
  UseGafpriPagesStorageProps,
  UseGafpriPagesStorageReturn,
  UseGafpriDataStorageProps,
  UseGafpriDataStorageReturn,
  StorageAttributes,
  UseGafpriApiStorageProps,
  UseGafpriApiStorageReturn,
  UseGafpriPaginationsStorageProps,
  UseGafpriPaginationsStorageReturn,
} from './storage';
export {
  useGafpriAttributesCashRegisterTypeUser,
  useGafpriApiCashRegisterType,
  useGafpriDataCashRegisterType,
  useGafpriPaginationsCashRegisterType,
  useGafpriPagesCashRegisterType,
  useGafpriAttributesCashRegisterType,
  useGafpriSubPagesCashRegisterType,
} from './cashRegisterType';
export type {
  UseGafpriAttributesCashRegisterTypeUserReturn,
  CashRegisterTypeUserAttributes,
  UseGafpriApiCashRegisterTypeReturn,
  UseGafpriApiCashRegisterTypeProps,
  UseGafpriDataCashRegisterTypeReturn,
  UseGafpriDataCashRegisterTypeProps,
  CashRegisterTypeAttributes,
  UseGafpriPaginationsCashRegisterTypeReturn,
  UseGafpriPaginationsCashRegisterTypeProps,
  UseGafpriPagesCashRegisterTypeReturn,
  UseGafpriPagesCashRegisterTypeProps,
  UseGafpriAttributesCashRegisterTypeReturn,
  UseGafpriSubPagesCashRegisterTypeReturn,
  CashRegisterTypeCurrenciesAttributes,
  CashRegisterCurrenciesAttributes,
} from './cashRegisterType';
export {
  useGafpriAttributesExpensesType,
  useGafpriPagesExpensesType,
  useGafpriDataExpensesType,
  useGafpriApiExpensesType,
  useGafpriPaginationsExpensesType,
} from './expensesType';
export type {
  UseGafpriAttributesExpensesTypeProps,
  UseGafpriAttributesExpensesTypeReturn,
  UseGafpriPagesExpensesTypeProps,
  UseGafpriPagesExpensesTypeReturn,
  UseGafpriDataExpensesTypeProps,
  UseGafpriDataExpensesTypeReturn,
  UseGafpriApiExpensesTypeProps,
  UseGafpriApiExpensesTypeReturn,
  UseGafpriPaginationsExpensesTypeReturn,
} from './expensesType';
export {
  useGafpriAttributesExpenses,
  useGafpriDataExpenses,
  useGafpriPagesExpenses,
  useGafpriApiExpenses,
  useGafpriPaginationsExpenses,
} from './expenses';
export type {
  UseGafpriAttributesExpensesReturn,
  UseGafpriDataExpensesReturn,
  UseGafpriDataExpensesProps,
  UseGafpriPagesExpensesReturn,
  UseGafpriApiExpensesReturn,
  UseGafpriApiExpensesProps,
  UseGafpriPaginationsExpensesReturn,
} from './expenses';
export {
  useGafpriAttributesIncome,
  useGafpriDataIncome,
  useGafpriPagesIncome,
  useGafpriApiIncome,
  useGafpriPaginationsIncome,
} from './income';
export type {
  UseGafpriAttributesIncomeReturn,
  UseGafpriDataIncomeReturn,
  UseGafpriDataIncomeProps,
  UseGafpriPagesIncomeReturn,
  UseGafpriApiIncomeReturn,
  UseGafpriApiIncomeProps,
  UseGafpriPaginationsIncomeReturn,
} from './income';
export {
  useGafpriAttributesPayment,
  useGafpriAttributesPaymentTransferCashRegister,
  useGafpriApiPaymentTransferCashRegister,
  useGafpriPagesPaymentTransferCashRegister,
  useGafpriAttributesPaymentTransferBank,
  useGafpriApiPaymentTransferBank,
  useGafpriPagesPaymentTransferBank,
  useGafpriPagesPayment,
  useGafpriSubPagesDepositPayment,
  useGafpriApiPayment,
} from './payment';
export type {
  UseGafpriAttributesPaymentReturn,
  PaymentAttributes,
  UseGafpriAttributesPaymentTransferCashRegisterReturn,
  UseGafpriApiPaymentTransferCashRegisterReturn,
  UseGafpriPagesPaymentTransferCashRegisterReturn,
  UseGafpriAttributesPaymentTransferBankReturn,
  UseGafpriApiPaymentTransferBankReturn,
  UseGafpriPagesPaymentTransferBankReturn,
  UseGafpriPagesPaymentReturn,
  UseGafpriPagesPaymentProps,
  UseGafpriSubPagesDepositPaymentReturn,
  UseGafpriApiPaymentReturn,
  UseGafpriApiPaymentProps,
} from './payment';
export {
  useGafpriApiBankType,
  useGafpriDataBankType,
  useGafpriPaginationsBankType,
  useGafpriPagesBankType,
  useGafpriAttributesBankType,
  useGafpriSubPagesBankType,
  useGafpriAttributesBankTransactions,
} from './bank';
export type {
  UseGafpriApiBankTypeReturn,
  UseGafpriApiBankTypeProps,
  UseGafpriDataBankTypeReturn,
  UseGafpriDataBankTypeProps,
  BankTypeAttributes,
  UseGafpriPaginationsBankTypeReturn,
  UseGafpriPaginationsBankTypeProps,
  UseGafpriPagesBankTypeReturn,
  UseGafpriPagesBankTypeProps,
  UseGafpriAttributesBankTypeReturn,
  UseGafpriSubPagesBankTypeReturn,
  UseGafpriAttributesBankTransactionsReturn,
  BankTransactionsAttributes,
} from './bank';
export { useGafpriAttributesCashTransactions } from './cashRegister';
export type {
  UseGafpriAttributesCashTransactionsReturn,
  CashTransactionsAttributes,
} from './cashRegister';
export {
  useGafpriApiAccountsReceivable,
  useGafpriDataAccountsReceivable,
  useGafpriPaginationsAccountsReceivable,
  useGafpriPagesAccountsReceivable,
  useGafpriAttributesAccountsReceivable,
  useGafpriAttributesCreditOpening,
  useGafpriAttributesCreditPayment,
} from './credits';
export type {
  UseGafpriApiAccountsReceivableReturn,
  UseGafpriApiAccountsReceivableProps,
  UseGafpriDataAccountsReceivableReturn,
  UseGafpriDataAccountsReceivableProps,
  AccountsReceivableAttributes,
  UseGafpriPaginationsAccountsReceivableReturn,
  UseGafpriPaginationsAccountsReceivableProps,
  UseGafpriPagesAccountsReceivableReturn,
  UseGafpriPagesAccountsReceivableProps,
  UseGafpriAttributesAccountsReceivableReturn,
  UseGafpriAttributesCreditOpeningReturn,
  CreditOpeningAttributes,
  UseGafpriAttributesCreditPaymentReturn,
  CreditPaymentAttributes,
} from './credits';
export {
  useGafpriAttributesGeneralPaymentMethods,
  useGafpriAttributesPaymentMethods,
  useGafpriPagesPaymentMethods,
} from './paymentMethods';
export type {
  UseGafpriAttributesPaymentMethodsReturn,
  PaymentMethodsAttributes,
  GeneralPaymentMethodsAttributes,
  UseGafpriAttributesGeneralPaymentMethodsReturn,
  UseGafpriPagesPaymentMethodsReturn,
} from './paymentMethods';
export {
  useGafpriAttributesOrderReturn,
  useGafpriPagesOrderReturn,
  useGafpriDataOrderReturn,
  useGafpriPaginationsOrderReturn,
} from './orderReturn';
export type {
  UseGafpriAttributesOrderReturnReturn,
  UseGafpriAttributesOrderReturnProps,
  UseGafpriPagesOrderReturnReturn,
  UseGafpriPagesOrderReturnProps,
  UseGafpriDataOrderReturnReturn,
  UseGafpriDataOrderReturnProps,
  OrderReturnAttributes,
  UseGafpriPaginationsOrderReturnReturn,
  UseGafpriPaginationsOrderReturnProps,
} from './orderReturn';
export {
  useGafpriApiWalletAccount,
  useGafpriDataWalletAccount,
  useGafpriPagesWalletAccount,
  useGafpriAttributesWalletAccount,
  useGafpriPaginationsWalletAccount,
} from './wallet';
export type {
  UseGafpriApiWalletAccountReturn,
  UseGafpriApiWalletAccountProps,
  UseGafpriDataWalletAccountReturn,
  UseGafpriDataWalletAccountProps,
  WalletAccountAttributes,
  UseGafpriPaginationsWalletAccountReturn,
  UseGafpriPaginationsWalletAccountProps,
  UseGafpriPagesWalletAccountReturn,
  UseGafpriPagesWalletAccountProps,
  UseGafpriAttributesWalletAccountReturn,
} from './wallet';
